categories: Categories
search: Search
tags: Tags
tagcloud: Tag Cloud
tweets: Tweets
prev: Previous
next: Next
comment: Comments
archive_a: Archives
archive_b: "Archives: %s"
page: Page %d
recent_posts: Recent Posts
newer: Newer
older: Older
share: Share
powered_by: Powered by
rss_feed: RSS Feed
category: Category
tag: Tag

routes: Routes
routes_subtitle: Popular hiking paths & camping places among tourists

four_season: Four Season Fun
four_season_subtitle: Bamyan is a great adventure at any time of year
spring: Spring
summer: Summer
autumn: Autumn
winter: Winter
now: now

map_title: Adventurous Spots
map_drag_tip: Drag map to see other parts!

events: Festivals
events_subtitle: Upcoming local cultural festivals and sport events

stories: Stories
stories_subtitle: Stories, expriences and adventures of people who visited Bamyan
