# Header
menu:
  About Bamyan: /about-bamyan
  Places to go: /categories/Places
  Things to do:
    Cultural Festivals: /categories/Festivals
    Sport Events: /tags/Sport/
    Try Local Foods: /cafes_restaurants
    Hiking: /categories/Routes
    Buy Souvenirs: /bamyan-souvenirs
    Stay Safe: /is-bamyan-safe
  Where to Stay: /hotels
  Virtual Tour: /virtual-tour
#  En:
#    فارسی: /persian
#    français: /french
#    中文: /chinese
#    Deutsche: /german
#    Español: /spanish
rss: /atom.xml

footer_menu:
  About Bamyan: /about-bamyan
  Where to Stay: /hotels
  Hiking Routes: /categories/Routes
  Where to buy souvenirs: /bamyan-souvenirs
  Try Local Dishes: /cafes_restaurants
  Places to Visit: /categories/Places
  Contact Us: /contact-us

footer_links:
  Festivals: /categories/Festivals
  Attractions: /categories/Places
  Cafes & Restaurants: /cafes_restaurants
  Hiking: /categories/Routes
  Shopping: /bamyan-souvenirs
  Activities: /tags/Sport/

phone_number: "+93 123 456 789"
email: "info@visit-bamyan.com"


tags:
  Featured: 'images/featured_tag.jpg'
  Sport: 'marathon-of-afghanistan/DSC_5678.jpg'

categories:
  Routes: 'images/routes_category.jpg'
  Places: 'city-of-screams-gholghola/ishkar-453563423.jpg'
  Festivals: 'bamyan-dambora-festival/136441590_14999483302191n.jpg'

# Content
excerpt_link: Read More
fancybox: true

# Sidebar
sidebar: right
widgets:
- category
- tag
- tagcloud
- archive
- recent_posts

# display widgets at the bottom of index pages (pagination == 2)
index_widgets:
# - category
# - tagcloud
# - archive

# widget behavior
archive_type: 'monthly'
show_count: false

# Miscellaneous
google_analytics: UA-20324816-40
gauges_analytics:
favicon: /assets/favicon.png
twitter: https://twitter.com/visitbamyan
twitter_user: visitbamyan
instagram: https://instagram.com/visitbamyan
youtube: https://youtube.com/visitbamyan
facebook: https://facebook.com/visitbamyan
fb_admins:
fb_app_id: 601479413669341

theme_color: '#ffbc00'
